# Generated by Django 5.1 on 2024-08-18 09:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_word', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='name_post')),
                ('comment', models.CharField(max_length=500)),
                ('sentence', models.TextField(default=None)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2024, 8, 18, 9, 57, 15, 969416, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Model_Post',
        ),
        migrations.AddField(
            model_name='answer_model',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='english.task_model'),
        ),
    ]
