# Generated by Django 5.1 on 2024-08-19 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_answer_model_task_model_delete_model_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
