# Generated by Django 5.1 on 2024-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_task_model_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_model',
            name='position',
        ),
        migrations.AddField(
            model_name='answer_model',
            name='position_correct',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='answer_model',
            name='position_wrong',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='answer_model',
            name='will_showed',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='answer_model',
            name='correct_word',
            field=models.TextField(default=None),
        ),
    ]
