# Generated by Django 5.1 on 2024-08-19 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_remove_answer_model_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Correct_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_word', models.TextField(default=None)),
                ('position_correct', models.IntegerField(default=None)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='english.task_model')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Wrong_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('will_showed', models.TextField(default=None)),
                ('position_wrong', models.IntegerField(default=None)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to='english.task_model')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer_Model',
        ),
    ]
