# Generated by Django 5.1 on 2024-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_answer_correct_model_answer_wrong_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='processed_sentence',
            field=models.TextField(default=None),
        ),
    ]
