# Generated by Django 5.1 on 2024-08-26 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_task_model_processed_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_sentence', models.TextField()),
                ('comment', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_sentence', models.TextField(null=True)),
                ('sentence', models.TextField(null=True)),
                ('fields', models.IntegerField(null=True)),
                ('answers', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer_wrong_model',
            name='task',
        ),
        migrations.CreateModel(
            name='Correct_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('phrase', models.CharField(max_length=301)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Wrong_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sentence')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer_Correct_Model',
        ),
        migrations.DeleteModel(
            name='Answer_Wrong_Model',
        ),
        migrations.DeleteModel(
            name='Task_Model',
        ),
    ]
