# Generated by Django 5.1 on 2024-08-26 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_sentence_remove_answer_wrong_model_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='sentence',
        ),
        migrations.AddField(
            model_name='sentence',
            name='correct_sentence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
