# Generated by Django 5.1 on 2024-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0010_alter_correct_answer_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='identifier',
            field=models.TextField(default='UniqueName_<django.db.models.fields.CharField>_2024-08-27 17:07:32.794067+00:00'),
        ),
    ]
